server:
  addr : 0.0.0.0
  port: 8080
  # debug info warn error
  loglevel: warn
  profile: dev
  logPath: .\log
  logName:  iris
swagger:
  enable: true
  ui_path: /swagger/
  json_path: /swagger/doc.json
pprof:
  enable: true
  port: 6060