server:
  addr : 0.0.0.0
  port: 8080
  # silent debug info warn error
  gorm_log_level: debug
  # debug info warn error
  zap_log_level: debug
  profile: dev
  configPath: .\configs
  logPath: .\log
  logName:  iris
  simple_stdout: false
swagger:
  enable: true
  ui_path: /swagger/
  json_path: /swagger/doc.json
pprof:
  enable: true
  port: 6060