dataSource:
  -
   db_file_path: device.db
   name: device
   type: sqlite
   slow_sql: 100 #ms
  -
   addr: 127.0.0.1
   port: 3389
   username: root
   password: 1234567
   idle_conn: 10
   max_conn: 20
   max_idle_time: 20
   max_life_time: 20
   charset: utf8mb4
   loc: Local
   db_name: test_db
   name: mysql
   type: mysql
   silent: false
   slow_sql: 100 #ms
kafka :
  host: 218.0.49.239
  port: 9092
redis:
  -
    host: 127.0.0.1:6379
    password:
    db: 10
    name: test1
  -
    host: 127.0.0.1:6379
    password:
    db: 10
    name: test2
oss:
  - name: test1
    ossBucket: test1
    ossEndpoint: test1
    accessKeyID: test1
    accessKeySecret: test1
  - name: test2
    ossBucket: test2
    ossEndpoint: test2
    accessKeyID: test2
    accessKeySecret: test2
mongo:
  - url: mongodb://test1:root@192.168.1.181:27000/test1
    name: test1
    tls: test1
  - url: mongodb://test2:root@192.168.1.181:27000/test1
    name: test2
    tls: test2
smtp:
  - host: test@qq.com
    port: 111
    sender: test
    password: test
    name: qqEmail