dataSource:
  -
   db_file_path: device.db
   name: device
   type: sqlite
   slow_sql: 100 #ms
  -
   addr: 127.0.0.1
   port: 3389
   username: root
   password: 1234567
   idle_conn: 10
   max_conn: 20
   max_idle_time: 20
   max_life_time: 20
   charset: utf8mb4
   loc: Local
   db_name: test_db
   name: mysql
   type: mysql
   slow_sql: 100 #ms
redis:
  -
    cluster_mode: 127.0.0.1:6379
    address:
    username:
    password:
    max_retry:
    db: 10
    pool_size:
    name: test1
  -
    cluster_mode: 127.0.0.1:6379
    address: ["127.0.0.1:6379"]
    username:
    password:
    max_retry:
    db: 10
    pool_size:
    name: test2
oss:
  - name: test1
    oss_bucket: test1
    oss_endpoint: test1
    access_key_id: test1
    access_key_secret: test1
  - name: test2
    oss_bucket: test2
    oss_endpoint: test2
    access_key_id: test2
    access_key_secret: test2
smtp:
  - host: test@qq.com
    port: 111
    sender: test
    password: test
    name: qqEmail